### ISSUE TITLE
Zugriff auf avrlib

### ISSUE THREAD

**Issue by Matzek2k** [cybaer/derMehrschritt#10]
Hey Sven, 

ich habe das makefile aktualisiert, so dass man nicht mehr in die fiese LockBits-Falle tappen kann. 

Jetzt wollte ich der makefile.mk in der avrlib ebenfalls updaten, aber ich kann nicht:

"remote: Permission to cybaer/avril.git denied to Matzek2k."

**Comment by cybaer** [comment]
Erledigt
